hydra:
  run:
    dir: ../results/${experiment.name}


experiment:
  name: 'name'
  ss: 'f0'
  rf: 'r0'
  version: 'v2' #'n100'

  plot: True

  run_name:
  folder: ${experiment.name}
  dir: ../results/${experiment.name}
  device: 'cpu'
  verbose: False
  seed: 0
  debug: True
  tqdm: True

defaults:
  - env: hl23net
  - agent: iql
  - _self_

agent:
  device: ${experiment.device}
  bufferid: ${env.name}_${experiment.ss}_${experiment.rf}_${experiment.version} # 'ballnstick_f0_r0_v2'
