hydra:
  run:
    dir: ../results/${experiment.name}


experiment:
  name: 'name'
  bufferid: 'test' #'ballnstick_f0_r0_v2'
  run_name:
  folder: ${experiment.name}
  dir: ../results/${experiment.name}
  device: 'cpu'
  verbose: False
  seed: 0
  debug: True
  tqdm: True

defaults:
  - env: hl23net
  - agent: iql
  - _self_

agent:
  device: ${experiment.device}
