agent: 'a2c'
debug: False

n_fc_hidden: 64

max_steps: 1e6
alpha: 0.005
tau: 0.7
gamma: 0.997
beta: 3.0
lr: 3e-4

batch_size: 16 # the mini_batch size
replay_buffer_size: 1024 # total <s,a,r,s'> pairs
